/**
 * Generated from command-code@1.56.0 reference/models.md.
 * Update with the upstream model reference before changing this snapshot.
 */

import type { SubscriptionPlan } from "./plan-types.ts"

export const COMMAND_CODE_MODEL_CATALOG_VERSION = "1.56.0"

export const MODEL_MIN_PLAN: Readonly<Record<string, SubscriptionPlan>> = {
  "MiniMaxAI/MiniMax-M2.5": "go",
  "MiniMaxAI/MiniMax-M2.7": "go",
  "MiniMaxAI/MiniMax-M3": "go",
  "Qwen/Qwen3.6-Max-Preview": "go",
  "Qwen/Qwen3.6-Plus": "go",
  "Qwen/Qwen3.7-Flash": "go",
  "Qwen/Qwen3.7-Max": "go",
  "Qwen/Qwen3.7-Plus": "go",
  "Qwen/Qwen3.8-27B": "go",
  "Qwen/Qwen3.8-Flash": "go",
  "Qwen/Qwen3.8-Max": "go",
  "Qwen/Qwen3.8-Max-0902": "go",
  "Qwen/Qwen3.8-Omni-Flash": "go",
  "claude-fable-5": "max",
  "claude-fable-5-1": "max",
  "claude-haiku-4-5-20251001": "pro",
  "claude-opus-4-7": "max",
  "claude-opus-4-8": "max",
  "claude-opus-5": "max",
  "claude-sonnet-4-6": "pro",
  "claude-sonnet-5": "pro",
  "deepseek/deepseek-v4-flash": "go",
  "deepseek/deepseek-v4-flash-fast": "go",
  "deepseek/deepseek-v4-flash-vision-exp": "go",
  "deepseek/deepseek-v4-pro": "go",
  "deepseek/deepseek-v4.1-flash": "go",
  "google/gemini-3.1-flash-lite": "pro",
  "google/gemini-3.5-flash": "pro",
  "google/gemini-3.5-flash-lite": "pro",
  "google/gemini-3.6-flash": "pro",
  "google/gemini-3.7-flash": "goat",
  "google/gemini-3.8-flash": "goat",
  "gpt-5.3-codex": "pro",
  "gpt-5.4": "pro",
  "gpt-5.4-mini": "pro",
  "gpt-5.5": "pro",
  "gpt-5.6-luna": "go",
  "gpt-5.6-sol": "goat",
  "gpt-5.6-terra": "pro",
  "gpt-6-astra": "max",
  "inclusionai/ling-3.0-flash-sante:free": "go",
  "meituan/LongCat-2.0:free": "go",
  "meta/muse-spark-1.1": "pro",
  "meta/muse-spark-1.2": "goat",
  "meta/muse-spark-1.2-contributor": "go",
  "meta/muse-spark-1.3": "goat",
  "meta/muse-spark-1.3-contributor": "go",
  "moonshotai/Kimi-K2.5": "go",
  "moonshotai/Kimi-K2.6": "go",
  "moonshotai/Kimi-K2.7-Code": "go",
  "moonshotai/Kimi-K2.7-Code-Highspeed": "go",
  "moonshotai/Kimi-K3": "go",
  "nvidia/nemotron-3-ultra-550b-a55b": "go",
  "poolside/laguna-s-2.1-free": "go",
  "sakana/fugu-ultra": "max",
  "stepfun/Step-3.5-Flash": "go",
  "stepfun/Step-3.7-Flash": "go",
  "tencent/hy3-paid": "go",
  "tencent/hy4-preview": "go",
  "thinkingmachines/inkling": "go",
  "thinkingmachines/inkling-small": "go",
  "xai/grok-4.5": "go",
  "xai/grok-4.6": "goat",
  "xiaomi/mimo-v2.5": "go",
  "xiaomi/mimo-v2.5-pro": "go",
  "z-ai/glm-5.3-flash": "go",
  "zai-org/GLM-5": "go",
  "zai-org/GLM-5.1": "go",
  "zai-org/GLM-5.2": "go",
  "zai-org/GLM-5.2-Fast": "go",
  "zai-org/GLM-5.3": "go",
}
